server:
  port: 80
---
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
---
spring.profiles: logging-info
logging:
  file: d:/shch/logs/log-file.log
  level:
    org.thymeleaf: WARN
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
    org.quartz.core: WARN
    org.h2.server.web: WARN
---
spring.profiles: logging-debug
logging:
  file: d:/shch/logs/log-file.log
  level:
    org.thymeleaf: WARN
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
    org.quartz.core: WARN
    org.h2.server.web: WARN
---
spring.profiles: logging-daily
logging:
  config: classpath:logback-spring.xml